matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      script:
        - cross-env LIMIT=4096 increase-memory-limit
        - yarn run build-gui
        - yarn run fetch
        - yarn run compile --max-old-space-size=4096
        - yarn run builder --mac -c.mac.identity=null
    - os: linux
      language: node_js
      node_js: "10"
      script:
        - cross-env LIMIT=4096 increase-memory-limit
        - yarn run build-gui
        - yarn run fetch
        - yarn run compile --max-old-space-size=4096
        - yarn run builder --linux
    - os: windows
      language: node_js
      node_js: "10"
      script:
        - cross-env LIMIT=4096 increase-memory-limit
        - yarn run build-gui
        - yarn run fetch
        - yarn run compile --max-old-space-size=4096
        - yarn run builder --win --ia32 --x64

before_install:
  - npm install -g increase-memory-limit
  - git clone https://github.com/Clipteam/clipcc-gui.git ../clipcc-gui

install:
  - cd ../clipcc-gui
  - yarn && yarn link
  - cd ../clipcc-desktop
  - yarn && yarn link clipcc-gui
