matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      script:
        - yarn run build-gui
        - yarn run fetch
        - yarn run compile
        - yarn run builder --mac
    - os: linux
      language: node_js
      node_js: "10"
      script:
        - yarn run dist
    - os: windows
      language: node_js
      node_js: "10"
      script:
        - yarn run build-gui && yarn run fetch && yarn run compile
        - yarn run builder --win --ia32 --x64

env:
  - NODE_ENV=production

before_install:
  - git clone https://github.com/Clipteam/clipcc-gui.git ../clipcc-gui
  - cd ../clipcc-gui
  - yarn --pure-lockfile && yarn link
  - cd ../clipcc-desktop
  - yarn --link-duplicates --pure-lockfile && yarn link clipcc-gui
