matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      script:
        - yarn run dist --mac
    - os: linux
      language: node_js
      node_js: "10"
      script:
        - yarn run dist --linux
    - os: windows
      language: node_js
      node_js: "10"
      script:
        - yarn run dist --win --ia32 --x64

before_install:
  - git clone https://github.com/Clipteam/clipcc-gui.git ../clipcc-gui
  - npm install -g increase-memory-limit

install:
  - cd ../clipcc-gui
  - yarn && yarn link
  - cd ../clipcc-desktop
  - yarn && yarn link clipcc-gui
  - increase-memory-limit
